{
 "title": "Node Temperature",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_uname_info, nodename)"
   },
   {
    "name": "instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Instance ($instance) - stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~\"$instance\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=~\"$instance\"}[$__interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=~\"$instance\"})\n)\n",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"node-exporter\", instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  { "title": "Instance ($instance) - stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~\"$instance\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=~\"$instance\"}[$__interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=~\"$instance\"})\n)\n",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"node-exporter\", instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  { "title": "Instance ($instance) - stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~\"$instance\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=~\"$instance\"}[$__interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=~\"$instance\"})\n)\n",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=\"node-exporter\", instance=~\"$instance\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"node-exporter\", instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  }
 ]
}